name: Rust

on:
  push:
    branches: [ "main-branch" ]
  pull_request:
    branches: [ "main-branch" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Add Lunar packages
      run: sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ mantic universe" 
    - name: Install JpegXL
      run: sudo apt-get update && sudo apt-get install -y liblcms2-2=2.14-2 libjxl-dev
    - name: Build
      run: cargo build --verbose --features default,libjxl,exiftool
    - name: Run tests
      run: cargo test --verbose
